CREATE TABLE members(
	id SMALLINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(99) NOT NULL,
	email VARCHAR(255),
	last_activity TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	is_admin TINYINT DEFAULT 0,
	is_mojang_account TINYINT
);
CREATE UNIQUE INDEX id ON members(id);

CREATE TABLE news(
	id SMALLINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	title VARCHAR(50),
	body LONGTEXT NOT NULL,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	author VARCHAR(50) NOT NULL
);
CREATE UNIQUE INDEX id ON news(id);

CREATE TABLE tokens(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	token VARCHAR(50) NOT NULL,
	generate_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	expire_date TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX id ON tokens(id);



-- Insert default user with admin rights
INSERT INTO members (username, password, is_admin) VALUES ("tugapower", "632fbf37cdcfe7824d2d0b4a0a8066fb", 1);